services:

  postgresql:
    image: postgres:12-alpine3.19
    container_name: zelda_cookbook
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: